### ISSUE TITLE
Cell sizes incorrect when flipping from notebook to dashboard view 

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#57] opened 2015-10-27 13:00 UTC
![screen shot 2015-10-27 at 8 58 25 am](https://cloud.githubusercontent.com/assets/153745/10758631/044faf4c-7c89-11e5-976c-8af974a6c12c.png)

Tapping the browser window size fixes the problem immediately:

![screen shot 2015-10-27 at 8 59 54 am](https://cloud.githubusercontent.com/assets/153745/10758646/1a9f51a8-7c89-11e5-8aba-30f2296f51fe.png)

**Comment by parente** [comment] 2015-10-27 13:01
Going from notebook -> layout -> dashboard view does not hit the bug. I suspect it's because the Jupyter headers / toolbar are hiding at the same time the layout is being computed. Sequence them?

**Comment by jhpedemonte** [comment] 2015-10-27 20:11
We couldn't reproduce this, at least not with latest code. But we did see a couple of other cases where we weren't waiting for the resize transition to end before letting the cell contents know they could resize. Those are fixed by reference PR.

**Comment by parente** [comment] 2015-10-27 20:56
I can't reproduce original with your fix. I didn't roll back to see if it was already fixed on master too. I was using the image deployed last Thursday at jupyter.cloudet.xyz. Not sure if anything went in since then that would have fixed this. :/

**Comment by jhpedemonte** [comment] 2015-10-28 22:08
OK, I figured out how to reproduce this exact issue:

1. Open Meetup Outreach demo.
2. Run all.
3. Switch to one of the Dashboard views.

-> overlapping cells in the **Upcoming Meetups** list.

The issue is that in `setInteractive` we are calling the `complete` callback (which invokes `PolymerSupport.notifyResizeAll()`) *before* the Gridstack container has finished resizing. We need wait for the transition to finish before invoking `complete`.

**Closed** 2015-10-30 14:19 UTC
Labels: bug, jhpedemonte/dalogsdon
