### ISSUE TITLE
Contents can overflow dashboard cell boundaries, overlap other cells

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/dashboards#53] opened 2015-10-26 21:39 UTC
In Layout mode, 

1. Add cells to be displayed in View mode.
2. Resize one of the cells to a much larger size, such that it overlaps existing cells.
3. The overlapped cells are now underneath the enlarged cell.
4. I now have to reposition all the overlapped cells.

When I resize a cell to make it larger, I think I'd like any cells that are being overlapped to be pushed beneath the one I'm enlarging.  Less work for me.

**Comment by dalogsdon** [comment] 2015-10-26 21:54
We haven't seen this issue in our testing. The normal behavior is to push the cells out of the way. Can you post either a screenshot or a notebook that reproduces the issue?

**Comment by jtyberg** [comment] 2015-10-26 23:01
Actually, the problem only seems to occur with cells that contain images/plots.  The cell boundaries do not always "contain" the image.  I didn't even realize that I did not size the cell correctly.  I kinda wish it wouldn't let me do that.
 
<img width="516" alt="large_overlap" src="https://cloud.githubusercontent.com/assets/359081/10744808/f16f9516-7c12-11e5-95ba-844414690b65.png">

**Comment by parente** [comment] 2015-10-27 01:01
Maybe if we reversed the original thinking and clipped at the grid cell boundaries it would be less surprising? The problem then is that the notebook author can't always predict what the max size of a cell will be (e.g., table) and overflow is beneficial in that case.

**Comment by parente** [comment] 2015-10-27 15:22
Maybe indicate where cell ends and overlap begins? Maybe revisit if clipping or scrolling within the cell is possible?

Investigation required.

**Comment by jhpedemonte** [comment] 2015-10-27 16:18
The main reason we don't hide overflow of cells is due to menus. With `overflow:hidden`, menus are clipped at that bottom of the cell.  Side effect is that some other elements also leak out, as seen above.

**Comment by jhpedemonte** [comment] 2015-10-27 16:27
One option: make borders of cells appear above cell contents, as seen below:

![screen shot 2015-10-27 at 11 27 10 am](https://cloud.githubusercontent.com/assets/711365/10764781/b3a9b532-7c9d-11e5-84c6-d694ba3e0351.png)

**Comment by jhpedemonte** [comment] 2015-10-27 16:49
Second option: use JavaScript to calculate the height of the cell content, and don't allow cell to be sized any smaller. This might be frustrating to users, though, since it removes some control -- it's possible a user would want there to be overflow.

**Comment by jhpedemonte** [comment] 2015-10-27 16:50
Also, it should be noted that when first going into dashboard view (no previous dashboard data) and when doing a show all, the cell is properly sized to contain the cell contents as they currently exist. So the only way to get overflow are: (1) the user resizes smaller than content, as Justin did in screenshot above; (2) there is a widget (such as a menu) which increases in height.

**Comment by jtyberg** [comment] 2015-10-27 17:15
Actually, I've found that during initial sizing of cell, to make it larger, the content can leak outside the cell boundary, even if I only ever increase the cell size.  For example, when increasing  in one direction, say width, an image within the cell increases in both width and height.  Since the aspect ratio of the bounding box is not constrained, it's rather easy to get overlap when only making the cell bigger.

**Comment by parente** [comment] 2015-10-27 17:16
I like option #1 for its simplicity in comparison to #2.

**Comment by dalogsdon** [comment] 2015-10-27 18:20
> when first going into dashboard view (no previous dashboard data) and when doing a show all, the cell is properly sized to contain the cell contents as they currently exist

When sizing a cell, we set a temporary width on the cell to cause text cells to automatically wrap after a certain point so not all text cells take the full width. This causes images larger than that size to be sized smaller than their true size. Resizing these images to be larger could then cause an overflow.

**Comment by dalogsdon** [comment] 2015-10-27 19:19
PR #66 resolves this using option 1, showing cell borders always.

**Comment by parente** [comment] 2015-10-27 21:00
@jtyberg give it a whirl and see if it's good enough or not.

**Comment by parente** [comment] 2015-10-30 18:22
Closing. Can reopen if it's not good enough in practice.

**Closed by parente** 2015-10-30 18:22 UTC
Labels: jhpedemonte/dalogsdon, question
