### ISSUE TITLE
In Layout mode, I really, REALLY want to drag and position cells by selecting anywhere in the cell.

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/dashboards#52] opened 2015-10-26 21:19 UTC
When positioning cells in Layout mode, I constantly find myself clicking and dragging the cell body to move cells, only to be reminded each time that it doesn't work that way.  I then squint and locate the little move icon in the upper left corner of the cell and try again.  5 seconds later, I do the same for the next cell.  Doh!

**Comment by dalogsdon** [comment] 2015-10-26 22:01
I agree that it is more intuitive to grab anywhere to drag. The reason there is a drag handle is that the cell output may contain widgets that are interactive, so we did not want the dragging to interfere with the interaction.

However, now that we have a 'View' mode in addition to a 'Layout' mode, we could use 'Layout' mode for dragging anywhere on the cell, blocking mouse interaction with any cell output. Then 'View' mode would allow interacting with the outputs of each cell.

**Comment by jtyberg** [comment] 2015-10-27 00:42
I can't speak for everyone, but when I'm in Layout mode, I'm thinking about cell position and size.  So I like the idea of favoring those interactions over interactions with widgets.  I wonder what others think.  I may be in the minority.

**Comment by parente** [comment] 2015-10-27 01:13
I've found myself interacting with a cell in layout mode to see if dynamic content fits in the cell or not. I'd go nuts flipping between layout and view to get that right.

**Comment by lbustelo** [comment] 2015-10-27 01:39
I'm not a fan of modes. 

Maybe when you hover, a larger frame and drag target appears around that does not interfere with content. 

Gino B.

**Comment by Lull3rSkat3r** [comment] 2015-10-27 14:57
Can we put the drag handle around the entire border? Have the very edge be for resizing and have a small border for dragging. Now that I am writing it out seems a little wonky, but maybe will seed some innovation :cow:

**Comment by parente** [comment] 2015-10-27 14:59
Hotkey (Cmd) you hold while click/dragging to indicate "I want to move this" instead of "I want to interact with this"? Can be doc'ed somewhere / show up as a first time tooltip on drag?

**Comment by parente** [comment] 2015-10-27 15:48
Discussed that we should look into hotkey modifier approach with doc for it in a tooltip or something (to be opened separately). We will keep the current dragger icon too.

**Comment by dalogsdon** [comment] 2015-10-30 18:59
We will take the hotkey approach. Working on this with @jhpedemonte.

**Comment by jtyberg** [comment] 2015-10-30 20:26
:joy:  :+1:

**Comment by dalogsdon** [comment] 2015-10-30 21:47
Hold the Shift key to be able to drag anywhere on a dashboard cell. Each cell will display the move icon to indicate this.

![image](https://cloud.githubusercontent.com/assets/6362426/10858825/ec3d4dfc-7f25-11e5-861c-54928be3e483.png)

@jtyberg Give it a try when PR #91 is merged.

:octopus:

**Closed** 2015-11-02 16:25 UTC
Labels: question

**Comment by parente** [comment] 2015-11-02 16:27
Tested a bit. Confirmed that it doesn't have any effect in dashboard view or deployed dashboard (correct). Really tried to break it by holding shift while clicking outside browser and back to notebook mode. It does get "stuck" but pressing and releasing shift to reset things works fine.

@jtyberg Give feedback when you've got a chance to try it.

**Comment by jtyberg** [comment] 2015-11-14 00:00
Very nice. Using the Shift key and dragging works just fine.

The only thing I noticed is the dragging a cell is a bit laggy when I've got a lot of cells (50+) in my notebook.

**Comment by dalogsdon** [comment] 2015-11-16 15:47
Yes, the layout is all absolute positioned, CPU intensive. The decision could be either to improve performance or recommend that a dashboard has less than X cells, since typical dashboards have maybe 10 at the most. Additionally, we could look into an interface such as tabbing to increase content while improving performance by moving cells to other (non-rendered) Gridstack instances.

**Comment by jhpedemonte** [comment] 2015-11-16 16:31
Performance issues may be due to translucency. One solution may be to disable that in certain cases (lots of cells, slow machine, older browser, etc).
