### ISSUE TITLE
Layout information is lost when flipping between Grid and Report layouts

### ISSUE THREAD

**Issue by nitind** [jupyter-incubator/dashboards#235] opened 2016-05-04 22:13 UTC
Switching between grid and report layouts wipes irreversibly loses the layout information, not even preserving which cells should be visible or hidden. At the least, whether a cell is visible or not should me maintained.

**Comment by parente** [comment] 2016-05-04 23:16
This was discussed and is actually "by design" at the moment. As we look at cleaning up the metadata we track in the notebook going forward, we should be able to solve this cleanly. In the meantime, if anyone has a quickfix for retaining the `cell.metadata.urth.dashboard.layout` object between mode flips without having to change code everywhere that assumes the layout is reset, we should put it in.

**Comment by dalogsdon** [comment] 2016-05-05 14:37
We could save the previous layout information in `dashboard-metadata.js` when setting the `dashboardLayout`. Currently when the layout is set to a new value it clears all the metadata, wiping the layout.

**Comment by jhpedemonte** [comment] 2016-05-05 14:59
What about only carrying over whether a cell is hidden or not, since that applies to both layouts?

**Comment by parente** [comment] 2016-05-05 16:27
@nitind and I tried the obvious thing of leaving layout intact, but then hit issues with other parts of code seeing "layout" in place and screwing up. For example, start with report, leave empty layout intact, switch to grid. Grid puts all the cells full width. Try to drag them and they're totally screwed up and overlap.

I'm OK delaying this until we improve the metadata spec which should account for this + multiple layouts.

**Comment by parente** [comment] 2016-06-02 01:42
Fixed by #254.

**Closed by parente** 2016-06-02 01:42 UTC
Labels: bug
