### ISSUE TITLE
Directly loading a notebook with the 'dashboard' query parameter can cause a rendering error

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#10] opened 2015-09-29 03:28 UTC
1 Create the dashboard layout in the notebook.
2 Switch to 'View Dashboard' in the notebook.
3 Refresh the page and observe the dashboard rendering incorrectly.

This has only been seen on the whiskey dashboard notebook.

**Comment by parente** [comment] 2015-10-19 14:47
Recent experience:

1. jupyter.cloudet.xyz
2. Load whiskey notebook (or any other dashboard notebook)
3. Run All to get everything loaded
4. View Dashboard
5. Refresh **with cache disabled in Chrome** as many times as you like = Everything OK
6. Refresh **with cache enabled in Chrome** and every other time, get a requireJS timeout loading all extensions.

**Comment by jhpedemonte** [comment] 2015-10-22 21:55
We can no longer reproduce this issue on Chrome (also tried Firefox), against either our local server or against jupyter.cloudet.xyz. @parente, if you cannot reproduce, then suggest closing this.

**Closed** 2015-10-23 22:45 UTC
Labels: bug
